arguments:
  format: json
git_services:
- host: github.com
  repos:
  - redhat-appstudio/build-definitions
  - redhat-appstudio/e2e-tests
  - redhat-appstudio/infra-deployments
  - redhat-appstudio/integration-service
  token: "${GITHUB_TOKEN}"
  type: github
