arguments:
  format: json
git_services:
- host: github.com
  repos:
  - redhat-appstudio/build-definitions
  - redhat-appstudio/book
  - redhat-appstudio/docs.appstudio.io
  - redhat-appstudio/e2e-tests
  - redhat-appstudio/infra-deployments
  - redhat-appstudio/integration-service
  - konflux-ci/integration-examples
  - redhat-appstudio/hacbs-test
  - konflux-ci/clair-in-ci-db
  - konflux-ci/integration-service-utils
  - redhat-appstudio/tenants-config
  token: "${GITHUB_TOKEN}"
  type: github
