arguments:
  format: json
git_services:
- host: github.com
  repos:
  - konflux-ci/build-definitions
  - redhat-appstudio/book
  - redhat-appstudio/docs.appstudio.io
  - konflux-ci/e2e-tests
  - redhat-appstudio/infra-deployments
  - konflux-ci/build-service
  - konflux-ci/image-controller
  - containerbuildsystem/cachito
  - containerbuildsystem/cachi2
  - containerbuildsystem/atomic-reactor
  - containerbuildsystem/osbs-client
  - containerbuildsystem/pyarn
  - containerbuildsystem/dockerfile-parse 
  - containerbuildsystem/koji-containerbuild
  - containerbuildsystem/osbs-docs
  - containerbuildsystem/ansible-role-osbs-remote-hosts
  - containerbuildsystem/ansible-role-osbs-namespace
  - redhat-appstudio/tenants-config
  token: "${GITHUB_TOKEN}"
  type: github
